version: "3.8"

services:
  dms-mpi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dms_mpi_system
    command: ["-np", "4", "./dms", "dms.conf"]
    stdin_open: true
    tty: true
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge
