services:
  dms-mpi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dms_mpi_system
    command:
      [
        "mpirun",
        "--allow-run-as-root",
        "-np",
        "4",
        "./dms",
        "-n",
        "4",
        "-k",
        "100",
        "-t",
        "1024",
      ]
    stdin_open: true
    tty: true
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge
